name: Terraform Format
summary: Ensure Terraform files are formatted.
description: Ensure Terraform files are formatted.
capabilities:
  - type: checkout
  - type: checkrun
    fix_errors: true
runtime: bash
show: all
tags:
  - HCL
  - Formatting
default_configuration:
  installation:
    repo_languages:
      - HCL
memory: 512
storage: 1024
subscription_level: 0
packages:
  system:
    - unzip
  asdf:
    - plugin: terraform
      source: https://github.com/asdf-community/asdf-hashicorp.git
      default_version: 1.2.9
      versions:
        - 1.2.9
        - 1.1.9
        - 1.0.11
        - 0.15.5
        - 0.14.11
        - 0.13.7
        - 0.12.31