version: v2
name: Terraform Format
slug: terraform-format
type: content
summary: Ensure Terraform files are formatted.
description: Ensure Terraform files are formatted.
subscription_level: 1
default_configuration:
  installation:
    repo_languages:
      - HCL
subscribed_events:
  - pull_request.opened
  - pull_request.reopened
  - pull_request.synchronize
  - check_run.rerequested
  - check_run.requested_action
