name: Terraform Format
slug: terraform-fmt
type: content
subscribed_events:
  - pull_request.opened
  - pull_request.reopened
  - pull_request.synchronize
  - check_run.rerequested
  - check_run.requested_action
